/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-tint": "#005cbb",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#1b1b1d",
        "tertiary": "#9b3f00",
        "surface": "#faf8fe",
        "tertiary-fixed": "#ffdbcb",
        "on-secondary-container": "#636264",
        "inverse-surface": "#2f3034",
        "surface-bright": "#faf8fe",
        "primary-fixed": "#d7e2ff",
        "background": "#faf8fe",
        "tertiary-fixed-dim": "#ffb693",
        "surface-container-highest": "#e3e2e7",
        "on-tertiary-fixed-variant": "#7a3000",
        "on-secondary": "#ffffff",
        "surface-variant": "#e3e2e7",
        "on-surface": "#1a1b1f",
        "on-primary-fixed": "#001b3f",
        "inverse-primary": "#abc7ff",
        "on-surface-variant": "#414753",
        "surface-dim": "#dad9df",
        "primary-fixed-dim": "#abc7ff",
        "on-background": "#1a1b1f",
        "inverse-on-surface": "#f1f0f5",
        "tertiary-container": "#c25100",
        "on-tertiary-fixed": "#341000",
        "surface-container-lowest": "#ffffff",
        "outline": "#717785",
        "primary-container": "#0071e3",
        "outline-variant": "#c1c6d6",
        "secondary-fixed-dim": "#c8c6c8",
        "on-secondary-fixed-variant": "#474649",
        "on-primary-fixed-variant": "#00458f",
        "secondary-container": "#e2dfe1",
        "error-container": "#ffdad6",
        "surface-container-low": "#f4f3f8",
        "on-tertiary": "#ffffff",
        "surface-container": "#eeedf3",
        "on-error": "#ffffff",
        "secondary": "#5f5e60",
        "on-primary-container": "#fcfbff",
        "on-tertiary-container": "#fffaf9",
        "surface-container-high": "#e9e7ed",
        "secondary-fixed": "#e4e2e4",
        "on-error-container": "#93000a",
        "primary": "#0059b5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "window-padding": "24px",
        "sidebar-width": "260px",
        "space-xl": "24px",
        "space-2xs": "2px",
        "space-3xl": "40px",
        "space-xs": "4px",
        "space-2xl": "32px",
        "inspector-width": "320px",
        "space-sm": "8px",
        "space-md": "12px",
        "space-4xl": "48px",
        "space-base": "16px",
        "space-lg": "20px"
      },
      fontFamily: {
        "caption": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "mono-code": ["JetBrains Mono", "monospace"],
        "label-md": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "caption": ["10px", { "lineHeight": "12px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "title-lg": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.018em", "fontWeight": "600" }],
        "mono-code": ["12px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.005em", "fontWeight": "500" }],
        "title-sm": ["15px", { "lineHeight": "20px", "letterSpacing": "-0.012em", "fontWeight": "600" }],
        "body-md": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-lg": ["15px", { "lineHeight": "22px", "letterSpacing": "-0.008em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "display": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.022em", "fontWeight": "600" }],
        "title-md": ["17px", { "lineHeight": "22px", "letterSpacing": "-0.015em", "fontWeight": "600" }]
      }
    }
  },
  plugins: []
};
